/*
 *
 * Copyright 2013 Analog Devices Inc.
 *
 * Licensed under the GPL-2 or later.
 */

#ifndef _PORTMUX_H_
#define _PORTMUX_H_
#include <asm/arch/gpio.h>

#define PORTA_FER	0x31004000
#define PORTB_FER	0x31004080
#define PORTC_FER	0x31004100
#define PORTD_FER	0x31004180
#define PORTE_FER	0x31004200
#define PORTF_FER	0x31004280

#define PORTA_FER_SET	0x31004004
#define PORTB_FER_SET	0x31004084
#define PORTC_FER_SET	0x31004104
#define PORTD_FER_SET	0x31004184
#define PORTE_FER_SET	0x31004204
#define PORTF_FER_SET	0x31004284

#define PORTA_MUX	0x31004030
#define PORTB_MUX	0x310040b0
#define PORTC_MUX	0x31004130
#define PORTD_MUX	0x310041b0
#define PORTE_MUX	0x31004230
#define PORTF_MUX	0x310042b0

#define MAX_RESOURCES    MAX_GPIOS

#define P_IDENT(x)	((x) & 0x1FF)
#define P_FUNCT(x)	(((x) & 0x3) << 9)
#define P_FUNCT2MUX(x)	(((x) >> 9) & 0x3)
#define P_DEFINED	0x8000
#define P_UNDEF		0x4000
#define P_MAYSHARE	0x2000
#define P_DONTCARE	0x1000

/* UART Port Mux */
#define P_UART0_TX      (P_DEFINED | P_IDENT(GPIO_PF8) | P_FUNCT(0))
#define P_UART0_RX      (P_DEFINED | P_IDENT(GPIO_PF9) | P_FUNCT(0))
#define P_UART0_RTS     (P_DEFINED | P_IDENT(GPIO_PD5) | P_FUNCT(2))
#define P_UART0_CTS     (P_DEFINED | P_IDENT(GPIO_PD6) | P_FUNCT(2))

#define P_UART1_TX      (P_DEFINED | P_IDENT(GPIO_PF10) | P_FUNCT(0))
#define P_UART1_RX      (P_DEFINED | P_IDENT(GPIO_PF11) | P_FUNCT(0))
#define P_UART1_RTS     (P_DEFINED | P_IDENT(GPIO_PE0) | P_FUNCT(2))
#define P_UART1_CTS     (P_DEFINED | P_IDENT(GPIO_PE14) | P_FUNCT(1))

#define P_UART2_TX      (P_DEFINED | P_IDENT(GPIO_PC12) | P_FUNCT(2))
#define P_UART2_RX      (P_DEFINED | P_IDENT(GPIO_PC13) | P_FUNCT(2))
#define P_UART2_RTS     (P_DEFINED | P_IDENT(GPIO_PA10) | P_FUNCT(1))
#define P_UART2_CTS     (P_DEFINED | P_IDENT(GPIO_PA11) | P_FUNCT(1))

/* SPI Port Mux */
#define P_SPI0_SCK      (P_DEFINED | P_IDENT(GPIO_PC1) | P_FUNCT(0))
#define P_SPI0_MISO     (P_DEFINED | P_IDENT(GPIO_PC2) | P_FUNCT(0))
#define P_SPI0_MOSI     (P_DEFINED | P_IDENT(GPIO_PC3) | P_FUNCT(0))
#define P_SPI0_RDY      (P_DEFINED | P_IDENT(GPIO_PC5) | P_FUNCT(2))

#define P_SPI0_SSEL1    (P_DEFINED | P_IDENT(GPIO_PC4) | P_FUNCT(0))
#define P_SPI0_SSEL2    (P_DEFINED | P_IDENT(GPIO_PC5) | P_FUNCT(0))
#define P_SPI0_SSEL3    (P_DEFINED | P_IDENT(GPIO_PC6) | P_FUNCT(0))
#define P_SPI0_SSEL4    (P_DEFINED | P_IDENT(GPIO_PA9) | P_FUNCT(2))
#define P_SPI0_SSEL5    (P_DEFINED | P_IDENT(GPIO_PF5) | P_FUNCT(2))
#define P_SPI0_SSEL6    (P_DEFINED | P_IDENT(GPIO_PF4) | P_FUNCT(2))
#define P_SPI0_SSEL7    (P_DEFINED | P_IDENT(GPIO_PD5) | P_FUNCT(0))

#define P_SPI1_SCK      (P_DEFINED | P_IDENT(GPIO_PC7) | P_FUNCT(0))
#define P_SPI1_MISO     (P_DEFINED | P_IDENT(GPIO_PC8) | P_FUNCT(0))
#define P_SPI1_MOSI     (P_DEFINED | P_IDENT(GPIO_PC9) | P_FUNCT(0))
#define P_SPI1_RDY      (P_DEFINED | P_IDENT(GPIO_PC11) | P_FUNCT(2))

#define P_SPI1_SSEL1    (P_DEFINED | P_IDENT(GPIO_PC10) | P_FUNCT(0))
#define P_SPI1_SSEL2    (P_DEFINED | P_IDENT(GPIO_PC11) | P_FUNCT(0))
#define P_SPI1_SSEL3    (P_DEFINED | P_IDENT(GPIO_PF11) | P_FUNCT(2))
#define P_SPI1_SSEL4    (P_DEFINED | P_IDENT(GPIO_PA14) | P_FUNCT(2))
#define P_SPI1_SSEL5    (P_DEFINED | P_IDENT(GPIO_PB2) | P_FUNCT(2))
#define P_SPI1_SSEL6    (P_DEFINED | P_IDENT(GPIO_PD7) | P_FUNCT(0))
#define P_SPI1_SSEL7    (P_DEFINED | P_IDENT(GPIO_PD6) | P_FUNCT(0))

#define P_SPI2_SCK      (P_DEFINED | P_IDENT(GPIO_PB14) | P_FUNCT(0))
#define P_SPI2_MISO     (P_DEFINED | P_IDENT(GPIO_PB10) | P_FUNCT(0))
#define P_SPI2_MOSI     (P_DEFINED | P_IDENT(GPIO_PB11) | P_FUNCT(0))
#define P_SPI2_RDY      (P_DEFINED | P_IDENT(GPIO_PC0) | P_FUNCT(1))
#define P_SPI2_D2       (P_DEFINED | P_IDENT(GPIO_PB12) | P_FUNCT(0))
#define P_SPI2_D3       (P_DEFINED | P_IDENT(GPIO_PB13) | P_FUNCT(0))

#define P_SPI2_SSEL1    (P_DEFINED | P_IDENT(GPIO_PB15) | P_FUNCT(0))
#define P_SPI2_SSEL2    (P_DEFINED | P_IDENT(GPIO_PF10) | P_FUNCT(1))
#define P_SPI2_SSEL3    (P_DEFINED | P_IDENT(GPIO_PC0) | P_FUNCT(0))
#define P_SPI2_SSEL4    (P_DEFINED | P_IDENT(GPIO_PD8) | P_FUNCT(2))
#define P_SPI2_SSEL5    (P_DEFINED | P_IDENT(GPIO_PA15) | P_FUNCT(2))
#define P_SPI2_SSEL6    (P_DEFINED | P_IDENT(GPIO_PA10) | P_FUNCT(2))
#define P_SPI2_SSEL7    (P_DEFINED | P_IDENT(GPIO_PB7) | P_FUNCT(2))

/* EMAC RGMII Port Mux */
#define P_MII0_ETxD0	(P_DEFINED | P_IDENT(GPIO_PB7) | P_FUNCT(0))
#define P_MII0_ETxD1	(P_DEFINED | P_IDENT(GPIO_PB8) | P_FUNCT(0))
#define P_MII0_ETxD2	(P_DEFINED | P_IDENT(GPIO_PB6) | P_FUNCT(0))
#define P_MII0_ETxD3	(P_DEFINED | P_IDENT(GPIO_PB5) | P_FUNCT(0))
#define P_MII0_ETxEN	(P_DEFINED | P_IDENT(GPIO_PB9) | P_FUNCT(0))
#define P_MII0_ETxCLK	(P_DEFINED | P_IDENT(GPIO_PB4) | P_FUNCT(0))

#define P_MII0_ERxD0	(P_DEFINED | P_IDENT(GPIO_PA13) | P_FUNCT(0))
#define P_MII0_ERxD1	(P_DEFINED | P_IDENT(GPIO_PA12) | P_FUNCT(0))
#define P_MII0_ERxD2	(P_DEFINED | P_IDENT(GPIO_PA14) | P_FUNCT(0))
#define P_MII0_ERxD3	(P_DEFINED | P_IDENT(GPIO_PA15) | P_FUNCT(0))
#define P_MII0_REFCLK	(P_DEFINED | P_IDENT(GPIO_PB0) | P_FUNCT(0))
#define P_MII0_RXDV		(P_DEFINED | P_IDENT(GPIO_PB2) | P_FUNCT(0))
#define P_MII0_RXER		(P_DEFINED | P_IDENT(GPIO_PB3) | P_FUNCT(0))

#define P_MII0_MDC		(P_DEFINED | P_IDENT(GPIO_PA11) | P_FUNCT(0))
#define P_MII0_MDIO		(P_DEFINED | P_IDENT(GPIO_PA10) | P_FUNCT(0))
#define P_MII0_CRS		(P_DEFINED | P_IDENT(GPIO_PB1) | P_FUNCT(0))

/*MSI*/
#define P_MSI0_D0	(P_DEFINED | P_IDENT(GPIO_PE12) | P_FUNCT(0))
#define P_MSI0_D1	(P_DEFINED | P_IDENT(GPIO_PE13) | P_FUNCT(0))
#define P_MSI0_D2	(P_DEFINED | P_IDENT(GPIO_PE14) | P_FUNCT(0))
#define P_MSI0_D3	(P_DEFINED | P_IDENT(GPIO_PE15) | P_FUNCT(0))
#define P_MSI0_D4	(P_DEFINED | P_IDENT(GPIO_PF0)  | P_FUNCT(0))
#define P_MSI0_D5	(P_DEFINED | P_IDENT(GPIO_PF1)  | P_FUNCT(0))
#define P_MSI0_D6	(P_DEFINED | P_IDENT(GPIO_PF2)  | P_FUNCT(0))
#define P_MSI0_D7	(P_DEFINED | P_IDENT(GPIO_PF3)  | P_FUNCT(0))
#define P_MSI0_CMD	(P_DEFINED | P_IDENT(GPIO_PF7)  | P_FUNCT(2))
#define P_MSI0_CLK	(P_DEFINED | P_IDENT(GPIO_PF4)  | P_FUNCT(0))
#define P_MSI0_CDb	(P_DEFINED | P_IDENT(GPIO_PC12) | P_FUNCT(1))
#define P_MSI0_INTb	(P_DEFINED | P_IDENT(GPIO_PC13) | P_FUNCT(1))


#define P_RGMII0 {\
	P_MII0_ETxD0, \
	P_MII0_ETxD1, \
	P_MII0_ETxD2, \
	P_MII0_ETxD3, \
	P_MII0_ERxD0, \
	P_MII0_ERxD1, \
	P_MII0_ERxD2, \
	P_MII0_ERxD3, \
	P_MII0_MDIO,  \
	P_MII0_MDC,   \
	P_MII0_REFCLK,\
	P_MII0_RXDV,  \
	P_MII0_ETxEN, \
	P_MII0_ETxCLK,\
	0}

int peripheral_request(unsigned short per, const char *label);
void peripheral_free(unsigned short per);
int peripheral_request_list(const unsigned short per[], const char *label);
void peripheral_free_list(const unsigned short per[]);

#endif				/* _PORTMUX_H_ */
