/*
 * U-boot - Configuration file for sc584 EZ-Kit board
 */

#ifndef __CONFIG_SC584_EZKIT_H
#define __CONFIG_SC584_EZKIT_H

#include <asm/mach-adi/common/config.h>

/*
 * Processor Settings
 */
#define CONFIG_ADI_CPU		"ADSP-SC584-0.1"
#ifdef CONFIG_SC58X_CHAIN_BOOT
# define CONFIG_LOADADDR	0x8b000000
# define CONFIG_RSA
#else
# define CONFIG_LOADADDR	0x89000000
#endif
#define CONFIG_DTBLOADADDR	"0x8b000000"
#define CONFIG_MACH_TYPE	MACH_TYPE_SC584_EZKIT

#define CONFIG_SYS_ARM_CACHE_WRITETHROUGH
#define CONFIG_SYS_BOOTM_LEN 0x1800000
#define CONFIG_SYS_TIMERBASE	TIMER0_CONFIG

/*
 * Memory Settings
 */
#define MEM_MT47H128M16RT
#define MEM_DMC0

#define	CONFIG_NR_DRAM_BANKS		1
#define CONFIG_SYS_SDRAM_BASE	0x89000000
#define CONFIG_SYS_SDRAM_SIZE	0x7000000
#define CONFIG_SYS_TEXT_BASE	0x89200000
#define CONFIG_SYS_LOAD_ADDR	0x0
#define CONFIG_SYS_INIT_SP_ADDR (CONFIG_SYS_SDRAM_BASE + 0x3f000)

#define CONFIG_SMC_GCTL_VAL	0x00000010
#define CONFIG_SMC_B0CTL_VAL	0x01007011
#define CONFIG_SMC_B0TIM_VAL	0x08170977
#define CONFIG_SMC_B0ETIM_VAL	0x00092231

#define CONFIG_SYS_MONITOR_LEN	(0)
#define CONFIG_SYS_MALLOC_LEN	(1024 * 1024)

/* Reserve 4MB in DRAM for Tlb, Text, Malloc pool, Global data, Stack, etc. */
#define CONFIG_SYS_MEMTEST_RESERVE_SIZE	(4 * 1024 * 1024)
#define CONFIG_SYS_MEMTEST_START		CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_MEMTEST_END			(CONFIG_SYS_SDRAM_BASE + \
				CONFIG_SYS_SDRAM_SIZE - \
				CONFIG_SYS_MEMTEST_RESERVE_SIZE)

/*
 * Network Settings
 */
#define ADI_CMDS_NETWORK
#define CONFIG_NETCONSOLE
#define CONFIG_NET_MULTI
#define CONFIG_DTBNAME		"sc584-ezkit.dtb"
#define CONFIG_HOSTNAME		"sc58x"
#define CONFIG_DESIGNWARE_ETH
#define CONFIG_DW_PORTS		1
#define CONFIG_DW_ALTDESCRIPTOR
#define CONFIG_MII
#define CONFIG_PHYLIB
#define CONFIG_PHY_TI
/*#define CONFIG_PHY_BCM89810*/
#define CONFIG_PHY_NATSEMI
#define CONFIG_ETHADDR	02:80:ad:20:31:e8

/*
 * SPI Settings
 */
#define CONFIG_CMD_SPI
#define CONFIG_ENV_SPI_MAX_HZ	5000000
#define CONFIG_SF_DEFAULT_SPEED	5000000
#define CONFIG_SPI_FLASH
#define CONFIG_SPI_FLASH_WINBOND
/*#define CONFIG_SPI_FLASH_MMAP*/

/*
 * USB Settings
 */
#define MUSB_HW_VERSION2
#define CONFIG_USB_STORAGE

/*
 * Env Storage Settings
 */
#define CONFIG_ENV_IS_IN_SPI_FLASH
#define CONFIG_ENV_SPI_BUS 2
#define CONFIG_ENV_SPI_CS 1

/*
 * Misc Settings
 */
#define CONFIG_SYS_NO_FLASH
#define CONFIG_UART_CONSOLE	0
#define CONFIG_BAUDRATE		115200
#define CONFIG_CMD_BOOTZ

#define CONFIG_BOOTCOMMAND	"run ramboot"
#define INITRAMADDR "0x8C000000"

#include <configs/sc_adi_common.h>

#endif
