# SPDX-License-Identifier: GPL-2.0-or-later
#
# (C) Copyright 2022 - Analog Devices, Inc.
#
# Written and/or maintained by Timesys Corporation
#
# Contact: Nathan Barrett-Morrison <nathan.morrison@timesys.com>
# Contact: Greg Malysa <greg.malysa@timesys.com>
#

obj-y	:= ../common-sc594-som/sc594-som.o
obj-$(CONFIG_SPL_BUILD) := ../common-sc594-som/sc594-som-spl.o


